version: "3"
services:
  backend:
    build:
      context: ./back # Asegúrate de que esta ruta coincida con el nombre de la carpeta
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front # Asegúrate de que esta ruta coincida con el nombre de la carpeta
    ports:
      - "80:80"
